### ISSUE TITLE
App crashes / doesn't work on Pixel 2 XL

### ISSUE THREAD

**Issue by crashniels** [liuzhushaonian/Lin15#6]
Hello. After seeing this module being used in a discord server i thought i would try it out on my Pixel 2 XL. Everything worked fine except for selecting an image. It said "editing is not supported..." coming from Google Photos. When uninstalling Google Photos the App crashes with a ActivityNotFoundException. I copied the crash URL here. https://del.dog/furifikiba.rb
![Screenshot_20190620-202508_Lin16](https://user-images.githubusercontent.com/39709384/59873093-8d384580-939b-11e9-93e2-5bd2385d8625.png)
![Screenshot_20190620-202816_Lawnchair](https://user-images.githubusercontent.com/39709384/59873094-8d384580-939b-11e9-9a1c-80b1029f6c0b.png)

Any help would be really appreciated. I would love to use this app / module. I hope I can help you with the things attached.

**Comment by liuzhushaonian** [comment]
This bug has been fixed
