### ISSUE TITLE
Lin16 在平板电脑上不工作

### ISSUE THREAD

**Issue by duzhaokun123** [liuzhushaonian/Lin15#7]
# 如题

**Comment by liuzhushaonian** [comment]
什么平板？Android系统是多少？ROM又是什么？xposed日志能提供吗？别一上来就提这种让人摸不着头脑的问题，我又不是神仙

**Comment by duzhaokun123** [comment]
在  0.5-bate 中出现了问题，之后的版本已经没有这个问题了。
