### ISSUE TITLE
建议 保持内部存储整洁

### ISSUE THREAD

**Issue by duzhaokun123** [liuzhushaonian/Lin15#8]
直接在`/sdcard/`里建文件夹有点烦人(特别对于不能插 SD卡 的设备)，能移到`/sdcard/Android/data/com.xp.legend.linX/files/`里吗？

**Comment by liuzhushaonian** [comment]
读取并放在sdcard上非我之所愿，为了解决Google相册不能剪切图片的问题，才在sdcard上创建了特殊的文件夹并存放文件，但是所有的手机都是可以使用的，并非只是针对插SD卡的手机，我的手机也是不能插SD卡，照样可以使用。而且在sdcard上创建的文件夹只有一个，且存放的文件也只有一个，并不会对sdcard造成什么污染，最新版也已经删除了剪切出来的图片，尽最大可能保持相册的整洁。至于为什么不放在你说的那个文件夹里，如果你明白Android的私有文件机制，你就会明白，放在那里的图片无法被剪切，就是那么简单。

**Comment by duzhaokun123** [comment]
那可以做到用完就删吗？包括`Pictures`里裁剪的残留
